### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by lubino** [kormax/apple-home-key#7]
Please, provide us some information of your progress/setbacks. Many people wants to help.

**Comment by kormax** [comment]
Hello.

The code is 99% ready, it's just undergoing closed preview & testing. 

Release before the end of this month.

**Comment by lubino** [comment]
Thank you for your fast response. It is very nice to hear this from you. Looking forward to be able to participate in any way.

**Comment by kormax** [comment]
I think that there will be opportunities for that. 

The software will emulate a homekit lock, but it actually ignores all commands apart from homekey-related ones (like opening/closing via app), would be useful if the other ones get implemented too.
Also, some HAP commands related to removing/suspending the keys were not done due to lack of testing.
The NFC part is 100% complete, so no opportunities there, but the data storage part can be changed. 

Anyway, you (and others) will see soon.

**Comment by kormax** [comment]
Also, if others are reading this, please take a look at the first NOTE section at the top of the page. Prepare all components, verify that they work via their respective demos, etc, so it wouldn't become a surprise that something doesn't work day 0.

**Comment by juaurodri** [comment]
Hi @kormax, 
Thanks for your work on this.
Do you think will be possible to have this working on a esp device, for example, using esphome and connect with homebridge or HomeAssistant?

**Comment by kormax** [comment]
My example code is in Python - so PC (or an SBC) only, but it's entirely possible for someone to re-implement this code in C/C++ for a microcontroller, I don't see any reason why this cannot happen.

**Comment by kormax** [comment]
I hope that [this](https://github.com/kormax/apple-home-key-reader) solves your issue.
